export const ceoMenu = [
  { name: "Dashboard", path: "/dashboard", icon: "home" },
  { name: "HR Management", path: "/hr", icon: "users" },
  { name: "Finance", path: "/finance-manager/dashboard", icon: "dollar-sign" },
  { name: "Project Management", path: "/project-manager/dashboard", icon: "folder" },
  { name: "Employee", path: "/hr/employees", icon: "user" },
  { name: "Site Engineer", path: "/site-engineer/dashboard", icon: "tool" },
  { name: "Client", path: "/client/dashboard", icon: "briefcase" },
  { name: "BDA", path: "/business-development/dashboard", icon: "trending-up" },
  { name: "Leads / CRM", path: "/bda/leads", icon: "target" },
  { name: "Reports", path: "/reports", icon: "file-text" },
  { name: "Analytics", path: "/analytics", icon: "bar-chart-2" },
  { name: "Users", path: "/users", icon: "user" },
  { name: "Settings", path: "/settings", icon: "settings" },
];