export const ceoMenu = [
  { name: "Dashboard", path: "/dashboard", icon: "layout" },
  { name: "HR Management", path: "/hr", icon: "users" },
  { name: "Finance", path: "/finance-manager/dashboard", icon: "pie-chart" },
  { name: "Project Management", path: "/project-manager/dashboard", icon: "layers" },
  { name: "Employee", path: "/hr/employees", icon: "user-check" },
  { name: "Site Engineer", path: "/site-engineer/dashboard", icon: "map-pin" },
  { name: "Client", path: "/client/dashboard", icon: "award" },
  { name: "BDA", path: "/business-development/dashboard", icon: "compass" },
  { name: "Leads / CRM", path: "/bda/leads", icon: "filter" },
  { name: "Reports", path: "/reports", icon: "inbox" },
  { name: "Analytics", path: "/analytics", icon: "activity" },
  { name: "Users", path: "/users", icon: "shield" },
  { name: "Settings", path: "/settings", icon: "settings" },
];