export const ROLES = {
  CEO: "ceo",
  EMPLOYEE: "employee",
  FINANCE: "finance",
  MARKETING: "marketing",
  CLIENT: "client",
  SITE_ENGINEER: "site_engineer",
  BDA: "bda",
  PROJECT_COORDINATOR: "project_coordinator",
  PROJECT_MANAGER: "project_manager",
  QUANTITY_SURVEYOR: "quantity_surveyor",
  STRUCTURAL_ENGINEER: "structural_engineer",
  MEP_ENGINEER: "mep_engineer",
  PLANNING_ENGINEER: "planning_engineer",
  SAFETY_OFFICER: "safety_officer",
  QC_ENGINEER: "qc_engineer",
  ARCHITECT: "architect",
};
